from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS

# KEPRI fork addition: parallel batch node (upstream nodes.py left untouched).
from .kepri_batch_node import (
    NODE_CLASS_MAPPINGS as KEPRI_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as KEPRI_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS.update(KEPRI_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(KEPRI_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
